ministryofjustice/laa-criminal-legal-aid-schemas

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
Adds "completed" to the list of allowed application statuses.
> Add 'completed' to application statuses.

- lib/laa_crime_schemas/types/types.rb
- adds ReviewApplicationStatus type
- removes 'completed' from ApplicationStatus
> Add ReviewApplicationStatuses

- lib/laa_crime_schemas/types/types.rb
Add assessment completed status to review application statuses
> Add assessment completed status to review application statuses

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- spec/fixtures/application/1.0/application_returned_split_case.json
- spec/laa_crime_schemas/structs/return_details_spec.rb
Adds new split case return application fixture
> [CRIMAM-311] Add split case test fixture

- .github/CODEOWNERS
- .github/pull_request_template.md
Same CODEOWNERS as in our other repos.
Added a basic PR template suitable for this gem repo.
After this is merged I will configure the repo settings to auto-request a PR review from this team.
> Add CODEOWNERS and PR template files

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/application.json
- schemas/1.0/general/offence.json
- schemas/1.0/maat_application.json
Add enums from types to json schema.
[CRIMRE-333](https://dsdmoj.atlassian.net/browse/CRIMRE-333)
[CRIMRE-333]: https://dsdmoj.atlassian.net/browse/CRIMRE-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add enum from defined types to json schema.

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/maat_application.json
- spec/fixtures/application/1.0/maat_application.json
This attribute can be used to perform logic about DWP on MAAT.
https://dsdmoj.atlassian.net/browse/CRIMAP-450
> CRIMAP-450 Expose `means_passport` in MAAT json

- lib/laa_crime_schemas/structs/applicant.rb
- lib/laa_crime_schemas/types/types.rb
- schemas/1.0/general/applicant.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
Add benefit types to types for apply value object to use
https://dsdmoj.atlassian.net/browse/CRIMAP-575
> Add benefit types to types for apply value object to use

- lib/laa_crime_schemas/types/types.rb
> Crimap 696 mange without income types

- Gemfile.lock
- lib/laa_crime_schemas/structs/case_details.rb
- lib/laa_crime_schemas/structs/crime_application.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/application.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
Moves work stream attribute from case details level to crime application level
https://dsdmoj.atlassian.net/browse/CRIMAPP-93
> Move work stream attribute to crime application level

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
- spec/fixtures/application/1.0/means.json
- spec/spec_helper.rb
Add income_above_threshold to income_details 
Make other income_details optional for now
bump schema version
https://dsdmoj.atlassian.net/browse/CRIMAPP-131
> CRIMAPP-131 income above threshold

- Gemfile.lock
- lib/laa_crime_schemas/structs/crime_application.rb
- lib/laa_crime_schemas/structs/means_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
Adds `means_details` to main crime application struct. Bumps version.
https://dsdmoj.atlassian.net/browse/CRIMAPP-106
Is this the right way to do it?
> [CRIMAP-105] Allow rehydration for lost job in custody

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
Add employment status and ended within 3 months to income_details
https://dsdmoj.atlassian.net/browse/CRIMAPP-135
> [CRIMAPP-135] Add employment status and ended within 3 months to applicant

- lib/laa_crime_schemas/structs/income_details.rb
- schemas/1.0/means.json
> Make not-always-asked questions optional

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
Add freezing order attribute to income details
https://dsdmoj.atlassian.net/browse/CRIMAPP-205
> Add freezing order attribute to income details

- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Add employment_type and ended_employment_within_three_months attributes to fixtures
> Add employment_type attributes to fixtures

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Add has_savings to income_details
https://dsdmoj.atlassian.net/browse/CRIMAPP-212
> Add has_savings to income_details

- lib/laa_crime_schemas/structs/income_details.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Add client_owns_property to IncomeDetails and fixtures
https://dsdmoj.atlassian.net/browse/CRIMAPP-209
> Add client_owns_property to IncomeDetails

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
Rename WorkStreams and add coercion to the Type. 
[CRIMAPP-253](https://dsdmoj.atlassian.net/browse/CRIMAPP-253)
Required for the following PR: https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/481
[CRIMAPP-253]: https://dsdmoj.atlassian.net/browse/CRIMAPP-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-253 update work stream names

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
> Change homeless value to living on streets

- Gemfile.lock
- lib/laa_crime_schemas.rb
- lib/laa_crime_schemas/structs/means_details.rb
- lib/laa_crime_schemas/structs/outgoings_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
- spec/laa_crime_schemas/structs/means_details_spec.rb
Add outgoings details attributes to schema, struct and fixture
https://dsdmoj.atlassian.net/browse/CRIMAPP-227
> [CRIMAPP-227] Add outgoings details attributes to schema, struct and fixture

- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/structs/means_details.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/means.json
Move dependants from means details to income details
> [CRIMAPP-282] move dependants to income details

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
> [CRIMAPP-282] Update version

- Gemfile.lock
- lib/laa_crime_schemas/structs/means_details.rb
- lib/laa_crime_schemas/structs/outgoings_details.rb
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Add housing_payment_type, bump schema
https://dsdmoj.atlassian.net/browse/CRIMAPP-275
> Add housing_payment_type, bump schema

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/maat_application.json
- spec/fixtures/application/1.0/maat_application.json
> Add benefit type to MAAT schema and fixture

- Gemfile.lock
- lib/laa_crime_schemas/structs/applicant.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/applicant.json
Correspondence address type should not be required.
[CRIMAPP-419](https://dsdmoj.atlassian.net/browse/CRIMAPP-419)
PSE only cares about name and DOP, for example.
[CRIMAPP-419]: https://dsdmoj.atlassian.net/browse/CRIMAPP-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crimapp 419 submit pse

- Gemfile.lock
- lib/laa_crime_schemas/structs/means_details.rb
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
- spec/fixtures/application/1.0/means.json
- spec/laa_crime_schemas/structs/means_details_spec.rb
Agreed to remove as no longer required
> Remove employment status 

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
Update version to v1.0.41 and basic gems update
N/A
N/A
> [CHORE] Update gems and version v1.0.41

- lib/laa_crime_schemas.rb
- lib/laa_crime_schemas/structs/capital_details.rb
- lib/laa_crime_schemas/structs/saving.rb
- lib/laa_crime_schemas/types/types.rb
- schemas/1.0/general/saving.json
- schemas/1.0/means.json
- spec/fixtures/application/1.0/means.json
- spec/laa_crime_schemas/structs/capital_details_spec.rb
- spec/laa_crime_schemas/structs/saving_spec.rb
- spec/spec_helper.rb
[CRIMAPP-535](https://dsdmoj.atlassian.net/browse/CRIMAPP-535)
[CRIMAPP-535]: https://dsdmoj.atlassian.net/browse/CRIMAPP-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-535 add savings to schema

- Gemfile.lock
- lib/laa_crime_schemas/structs/capital_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
> Require savings on capital

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/maat_application.json
Add none benefit type to MAAT schema
https://dsdmoj.atlassian.net/browse/CRIMAPP-604
> [CRIMAPP-604] Add none benefit type to MAAT schema

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/means.json
`pays_council_tax` was missing from the means schema
https://dsdmoj.atlassian.net/browse/CRIMAPP-266
N/A
> [CRIMAPP-266] Add pays_council_tax to schema

- Gemfile.lock
- lib/laa_crime_schemas.rb
- lib/laa_crime_schemas/structs/capital_details.rb
- lib/laa_crime_schemas/structs/investment.rb
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/investment.json
- schemas/1.0/means.json
- spec/fixtures/application/1.0/means.json
- spec/laa_crime_schemas/structs/capital_details_spec.rb
- spec/laa_crime_schemas/structs/investment_spec.rb
[CRIMAPP-554](https://dsdmoj.atlassian.net/browse/CRIMAPP-554)
[CRIMAPP-554]: https://dsdmoj.atlassian.net/browse/CRIMAPP-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add investments to capital details

- Gemfile.lock
- lib/laa_crime_schemas.rb
- lib/laa_crime_schemas/structs/capital_details.rb
- lib/laa_crime_schemas/structs/national_savings_certificate.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/national_savings_certificate.json
- schemas/1.0/means.json
- spec/fixtures/application/1.0/means.json
- spec/laa_crime_schemas/structs/capital_details_spec.rb
- spec/laa_crime_schemas/structs/national_savings_certificates_spec.rb
Add National Savings Certificate to Capital Details
[CRIMAPP-582](https://dsdmoj.atlassian.net/browse/CRIMAPP-582)
[CRIMAPP-582]: https://dsdmoj.atlassian.net/browse/CRIMAPP-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add National Savings Certificates

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
> Add income benefit to fixture

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/investment.json
> Add share to investment type

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
> Bump schema

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/maat/means.json
- spec/fixtures/application/1.0/maat_application.json
> Fix naming errors in income payment enum and fixture

- Gemfile.lock
- lib/laa_crime_schemas/structs/applicant.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/applicant.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
- spec/fixtures/application/1.0/maat_application.json
Adds `last_jsa_appointment_date` attribute 
[CRIMAPP-441](https://dsdmoj.atlassian.net/browse/CRIMAPP-441)
[CRIMAPP-441]: https://dsdmoj.atlassian.net/browse/CRIMAPP-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-441] Add jsa last appointment date

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/maat_application.json
I missed the maat application schema definition file 
[CRIMAPP-441](https://dsdmoj.atlassian.net/browse/CRIMAPP-441)
[CRIMAPP-441]: https://dsdmoj.atlassian.net/browse/CRIMAPP-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-441] Add last jsa date to maat schema definition

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- spec/fixtures/application/1.0/application_returned.json
in addition to [#132](https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/132)
> Update application returned fixture

- Gemfile.lock
- lib/laa_crime_schemas/structs/applicant.rb
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/applicant.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
- spec/fixtures/application/1.0/maat_application.json
Adds residential status attributes
[CRIMAPP-776](https://dsdmoj.atlassian.net/browse/CRIMAPP-776)
[CRIMAPP-776]: https://dsdmoj.atlassian.net/browse/CRIMAPP-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-776] Add residential status attributes

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/means.json
Store answer to "Client has dependents?"
https://dsdmoj.atlassian.net/browse/CRIMAPP-757
Also makes other has_no questions consistent.
> CRIMAPP-757 store dependants answer

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- spec/fixtures/application/1.0/means.json
Update fixture to fix failing review spec
> [CRIMAPP-776] Update means fixture

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/applicant.json
- schemas/1.0/maat_application.json
> remove esa from residence type

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
Didn't notice the version comment in the last pr
> Correct schema version

- Gemfile.lock
- lib/laa_crime_schemas/structs/applicant.rb
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/applicant.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
Adds benefit check result attributes to schema 
[CRIMAPP-912](https://dsdmoj.atlassian.net/browse/CRIMAPP-912)
[CRIMAPP-912]: https://dsdmoj.atlassian.net/browse/CRIMAPP-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-912] add passporting benefit attributes

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- spec/laa_crime_schemas/types/types_spec.rb
Separate income and outgoing payments by "other" and "employment" payments 
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
> CRIMAPP-875 - Refactor Income and Outgoings payments

- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/structs/outgoings_details.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Rehydrate following employment attributes 
- outgoings.self_assessment_tax_bill
- income.applicant_other_work_benefit_received
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
> CRIMAPP-875 - Add income and outgoings attributes

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
Bump schema version to **v1.1.11**
> Update Schema version

- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/structs/outgoings_details.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Support 'self assessment tax bill' attributes and include it in income details
- applicant_self_assessment_tax_bill
- applicant_self_assessment_tax_bill_amount
- applicant_self_assessment_tax_bill_frequency
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
> CRIMAPP-875- Refactor self assessment tax bill

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
> Update schema v to 1.1.13

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Add partner employment attributes
https://dsdmoj.atlassian.net/browse/CRIMAPP-1002
> Add partner employment income attributes

- lib/laa_crime_schemas/structs/income_details.rb
- schemas/1.0/means.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/means.json
Remove 'partner_employments' array and use 'employments' array for **applicant** and **partner**
> Remove "partner_employments" from schema

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
> Update schema version to 1.1.17

- schemas/1.0/maat/means.json
- spec/fixtures/application/1.0/maat_application.json
Add employment income payment details calculated annually
- amount
- frequency
- income_tax
- national_insurance
- ownership_type
[CRIMAPP-1095](https://dsdmoj.atlassian.net/browse/CRIMAPP-1095)
[CRIMAPP-1095]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update MAAT schema

- Gemfile.lock
- lib/laa_crime_schemas/structs/provider_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/provider.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
- spec/laa_crime_schemas/structs/provider_details_spec.rb
> Add partner declaration values to struct

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/employment.json
Validate 'employment_income_payments' struct while submitting to datastore
https://dsdmoj.atlassian.net/browse/CRIMAPP-1095
> CRIMAPP-1095 :: MAAT :: Add attribute 'employment_income_payments' to income_details

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- spec/fixtures/application/1.0/means.json
Crime apply datastore is sending incorrect payment type in prod 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1169
> CRIMAPP-1169 - Crime apply datastore is sending incorrect payment type in prod

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
Add non-means tested work stream
[CRIMAPP-1183](https://dsdmoj.atlassian.net/browse/CRIMAPP-1183)
[CRIMAPP-1183]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1183] Add non-means tested work stream

- Gemfile.lock
- lib/laa_crime_schemas/structs/business.rb
- lib/laa_crime_schemas/version.rb
- spec/laa_crime_schemas/structs/business_spec.rb
> Update total income share sales type to amount

- Gemfile.lock
- lib/laa_crime_schemas/structs/crime_application.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/application.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
> Add is_means_tested attr to crime_application

- Gemfile.lock
- lib/laa_crime_schemas/structs/case_details.rb
- lib/laa_crime_schemas/version.rb
> Make appeal maat id non mandatory

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- spec/fixtures/application/1.0/means.json
Required to fix spec errors in review
> Add metadata to employment income

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/application.json
> Remove case type follow-on answers from required field

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/maat/means.json
- spec/fixtures/application/1.0/maat_application.json
Expose 'income_details' attributes to MAAT
- manage_without_income
- manage_other_details
https://dsdmoj.atlassian.net/browse/CRIMAPP-963
> [!IMPORTANT]  
> TODO:: Update schema version in Apply, Review and Datastore
> Expose 'How does your client manage with no income?' attributes to MAAT

- Gemfile.lock
- lib/laa_crime_schemas/structs/applicant.rb
- lib/laa_crime_schemas/structs/partner.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/applicant.json
- schemas/1.0/general/partner.json
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
- spec/fixtures/application/1.0/change_in_financial_circumstances.json
> [CRIMAPP-1181] Add has_arc attribute

- Gemfile.lock
- lib/laa_crime_schemas/structs/income_details.rb
- lib/laa_crime_schemas/version.rb
- spec/fixtures/application/1.0/application.json
- spec/fixtures/application/1.0/application_returned.json
- spec/fixtures/application/1.0/change_in_financial_circumstances.json
Add `client_in_armed_forces` and `partner_in_armed_forces` attributes.
[CRIMAPP-1300](https://dsdmoj.atlassian.net/browse/CRIMAPP-1300)
[CRIMAPP-1300]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1300] Add in_armed_forces attribute for client & partner

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
> update version to v1.2.8

- .github/workflows/main.yml
- Gemfile.lock
- laa-criminal-legal-aid-schemas.gemspec
- lib/laa_crime_schemas/version.rb
Support ruby 3.3.4
https://dsdmoj.atlassian.net/browse/CRIMAPP-1316
> Support ruby 3.3.4

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
Support decisions with Means test result
NB this removes schema types for IoJ and Means which would be a braking change were they used.
> Support MAAT decisions

- Gemfile.lock
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/decision.json
Adds missing result type.
IoJ can only be pass or fail.
Base on findings from: [CRIMAPP-1473](https://dsdmoj.atlassian.net/browse/CRIMAPP-1473)
[CRIMAPP-1473]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1473 add failmeioj

- Gemfile.lock
- lib/laa_crime_schemas/structs/decision.rb
- lib/laa_crime_schemas/types/types.rb
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/decision.json
Add overall_result and case_type to decisions
[CRIMAPP-1577](https://dsdmoj.atlassian.net/browse/CRIMAPP-1577)
[CRIMAPP-1577]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1569 add CourtType and OverallResult to decision

- Gemfile.lock
- lib/laa_crime_schemas/version.rb
- schemas/1.0/general/decision.json
Allow decisions without a court type (For example for Non-means)
[CRIMAPP-1590](https://dsdmoj.atlassian.net/browse/CRIMAPP-1590)
[CRIMAPP-1590]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow decisions without a court_type
