lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/structs/offence.rb
schemas/1.0/application.json
schemas/1.0/general/offence.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json

After this change is introduced in the datastore, new submitted applications will have to conform to the new format for offence dates (`date_from` and `date_to`).
However to keep compatibility and less disruptive with already submitted applications, the struct counterpart will still support a simple array and will not enforce the content of the objects in the array for the time being.
This will be enforced at a later time.

Update schema to support offence date ranges

---

lib/laa_crime_schemas.rb
lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/structs/return_details.rb
lib/laa_crime_schemas/types/types.rb
schemas/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/laa_crime_schemas/structs/crime_application_spec.rb
spec/laa_crime_schemas/structs/return_details_spec.rb

Add return_details to: Types, Structs, Schema, and fixtures.
[CRIMRE-52](https://dsdmoj.atlassian.net/browse/CRIMRE-52)
[CRIMRE-52]: https://dsdmoj.atlassian.net/browse/CRIMRE-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Crimre 52 return reason types

---

lib/laa_crime_schemas/types/types.rb

To allow for a case split by the CPS to be returned by the caseworker to the provider return reason type of split_case is needed

Add split_case return reason

---

README.md
lib/laa_crime_schemas/validator.rb
schemas/1.0/maat_application.json
spec/fixtures/application/1.0/maat_application.json
spec/fixtures/application/1.0/maat_application_invalid.json
spec/laa_crime_schemas/validator_spec.rb

Add a specific schema for MAAT.
This adds the initial version of the maat_application schema, which is designed to be used exclusively by the MAAT api.
We decided to create a separate schema to allow for changes to the main application schema used by Apply and Review without requiring updates to MAAT. Additionally, there are some attributes that are not necessary for MAAT.
We decided against using namespaces for the MAAT schema for a few reasons, primarily because it would necessitate modifying multiple utilities that come with this gem.

Add MAAT application schema

---

spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_completed.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/application_returned_split_case.json

Confirmed on staging that the offence class data is returned without 'Class' prefixed so the fixtures have been amended to reflect that
`#<LaaCrimeSchemas::Structs::Offence name=“Assault a person thereby occasioning them actual bodily harm” offence_class=“C” dates=[#<LaaCrimeSchemas::Structs::Offence::Date date_from=Thu, 10 Jan 1980 date_to=Thu, 10 Jan 1980>]>] irb(main):004:0>`
This change facilitates testing offence class calculation for [CRIMRE-250](https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960?modal=detail&selectedIssue=CRIMRE-250) in the datastore which uses the fixture data 
[CRIMRE-250]: https://dsdmoj.atlassian.net/browse/CRIMRE-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove unrequired class prefix in offence class data

---

lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/types/types.rb
schemas/1.0/application.json
schemas/1.0/maat_application.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_completed.json
spec/fixtures/application/1.0/application_invalid.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/application_returned_split_case.json
spec/fixtures/application/1.0/maat_application.json
spec/fixtures/application/1.0/maat_application_invalid.json

This serves a similar purpose to the already existing `ioj_passport`, so Review can know on what basis an application has been passported on means.
Also, as Apply now handles this more granularly, we need this information back when reading back applications from the datastore and for rehydration.
Existing applications in datastore lack this attribute, so we can either run a migration task or make the code on Apply/Review resilient with a sensible fallback.
Fixtures and schema updated and fixed some logical inconsistencies.

CRIMAP-331 Add `means_passport` attribute

---

Gemfile.lock
lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/structs/offence.rb
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_completed.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/application_returned_split_case.json

Added offence class at case level to allow for persistence of overall offence class to datastore - so that it is not calculated at time of api call. And is also available to Review to surface to the caseworker
https://dsdmoj.atlassian.net/browse/CRIMRE-312
Overall offence class calculation currently can calculate to nil -> do we want this to be 'Undefined'?
Overall offence class calculation currently outputs offence class as lowercase - can we upcase it?
We were also unable to set this attribute as mandatory because the calculation will not have taken place before the schma validation - is this another argument to calculate overall offence class in Apply?

Added offence class at case level

---

spec/laa_crime_schemas/types/types_spec.rb

Adding a test for the offence class type to ensure that changes to the offence class ranking (and which may cause breaking changes) are caught in testing as an equivalent test was removed in the datastore repo

Add test for offence class type

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/general/applicant.json
spec/laa_crime_schemas/structs/crime_application_spec.rb

Forces JSON schema constraint for correspondence_address_type to replicate Type/Struct enum constraint for the same field.
https://dsdmoj.atlassian.net/browse/CRIMRE-215
Bump minor version as it's a potential minor breaking change in terms of schema

[CRIMRE-215] Add enum constraint to correspondence_address_type

---

lib/laa_crime_schemas/structs/offence.rb
schemas/1.0/general/offence.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_completed.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/application_returned_split_case.json

On the back of this PR on Apply, we now can propagate this from Apply to Datastore, even tho we don't need it just now.
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/364
Marking attribute in the Struct as optional, because existing applications in the datastore will not have this.
Not bumping schemas version yet, as there is no need to release a new version just for this.
Will be bumped a bit later once we do some auditing of attributes, structs and schemas that is pending.
https://dsdmoj.atlassian.net/browse/CRIMAP-146

Add `passportable` bool attribute to offence object

---

Gemfile.lock
lib/laa_crime_schemas.rb
lib/laa_crime_schemas/structs/person.rb
lib/laa_crime_schemas/structs/pruned_application.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
schemas/1.0/maat_application.json
schemas/1.0/pruned_application.json
spec/fixtures/application/1.0/pruned_application.json
spec/laa_crime_schemas/structs/pruned_application_spec.rb
spec/laa_crime_schemas/validator_spec.rb

New struct, schema and fixture corresponding to a simplified, narrowed down, pruned representation of a crime application.
This will contain the basic details needed to present lists of applications to paginate throw them. Usually these lists don't require much detail, mainly status, first name, last name, reference, timestamps, and just in case some additional information about the type of application.
To be used in the datastore, when returning a paginated list of applications. Currently only affects Apply. No changes required for Review.
https://dsdmoj.atlassian.net/browse/CRIMAP-387
PRs to follow for Apply and Datastore.

CRIMAP-387 New pruned application schema and struct

---

.github/workflows/main.yml
.rubocop.yml
Gemfile.lock
laa-criminal-legal-aid-schemas.gemspec
lib/laa_crime_schemas.rb
lib/laa_crime_schemas/structs/applicant.rb
lib/laa_crime_schemas/structs/base_application.rb
lib/laa_crime_schemas/structs/case_details.rb
lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/structs/offence.rb
lib/laa_crime_schemas/structs/provider_details.rb
lib/laa_crime_schemas/structs/pruned_application.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/pruned_application.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/maat_application.json
spec/fixtures/application/1.0/pruned_application.json
spec/laa_crime_schemas/structs/case_details_spec.rb
spec/laa_crime_schemas/structs/offence_spec.rb
spec/laa_crime_schemas/structs/provider_details_spec.rb

Over the course of the last months we've been evolving the datastore and the submitted JSON documents, with new attributes, or changes to existing ones.
With the objective of not breaking the existing submitted applications every few days, we've been quite lenient in the way the Structs handle the existing data when reading back from the Datastore.
For instance, many attributes were marked as optional, as old data didn't have those. However new submitted applications will always have them now. Etc.
Made changes to the structs to support this. Also a small refactor to the existing structs to have separate `case_details` and `provider_details` and improved testing.
Note these are breaking changes with many of the existing applications in the datastore, so along with this, we would probably …

CRIMAP-388 Make the structs more strict

---

Gemfile.lock
lib/laa_crime_schemas/structs/offence.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/general/offence.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/laa_crime_schemas/structs/offence_spec.rb

There will be some changes on Apply to go along with this renaming.
No breaking changes, as the attribute is marked as optional on the Struct object. Also, no consumer was actually using the old attribute.
https://dsdmoj.atlassian.net/browse/CRIMAP-415

CRIMAP-415 Rename `passportable` to `slipstreamable`

---

Gemfile.lock
lib/laa_crime_schemas/structs/case_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
schemas/1.0/maat_application.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/maat_application.json
spec/laa_crime_schemas/structs/case_details_spec.rb

Removed no longer needed `appeal_with_changes_maat_id` attribute, because for both types of appeals, the attribute `appeal_maat_id` will be used.
Added a new `appeal_lodged_date` attribute, of type date.
The Struct is not enforcing presence of this new attribute, as existing applications in datastore lack it, but ideally should be made mandatory before going live.
https://dsdmoj.atlassian.net/browse/CRIMAP-427
Just as a sanity check, may I ask review devs to test this gem version in case it breaks something? I think it shouldn't if you were not using before the now removed `appeal_with_changes_maat_id` attribute.

CRIMAP-427 Refactor appeal attributes

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat_application.json
spec/fixtures/application/1.0/maat_application.json

It was discovered that “date signed” is a mandatory field in MAAT.  This will be provided by us by exposing a `declaration_signed_at` field for maat applications in the datastore. This PR updates the maat application schema to require the attribute. The minor version is also incremented.
[CRIMRE-387](https://dsdmoj.atlassian.net/browse/CRIMRE-387)
[CRIMRE-387]: https://dsdmoj.atlassian.net/browse/CRIMRE-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Require declaration_signed_at for maat applications

---

Gemfile.lock
lib/laa_crime_schemas/structs/return_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/laa_crime_schemas/structs/return_details_spec.rb

These small changes in the schema are needed for a bigger piece of work going on in the datastore to remove the ReturnDetails DB table and use instead a jsonb attribute in the existing CrimeApplications DB table.
The `returned_at` attribute in the schema `return_details` object is redundant as this attribute exists as top-level already, so I've removed it.
https://dsdmoj.atlassian.net/browse/CRIMAP-433

CRIMAP-433 Refactor return details

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat_application.json
spec/fixtures/application/1.0/maat_application.json

Removed the `interests_of_justice` array object, because MAAT does not need any of its content, and the only purpose of this attribute would have been to check if the array was empty or not, to trigger IoJ pass logic.
This is now explicitly done via a new boolean attribute, `ioj_bypass`, which will be `true` if the Interests of Justice page was skipped on Apply, meaning we didn't gather IoJ reasons, or `false` otherwise. It maps more directly to MAAT business rules and domain.
https://dsdmoj.atlassian.net/browse/CRIMAP-436
A new release will be generated, and changes in datastore are needed, together with this new gem release, to be fully working. Will raise a separate PR in datastore soon.

CRIMAP-436 MAAT schema changes related to IoJ pass

---

lib/laa_crime_schemas.rb
lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/structs/document.rb
schemas/1.0/application.json
schemas/1.0/general/document.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/maat_application.json
spec/laa_crime_schemas/structs/document_spec.rb

This PR is part of a wider piece of work to serialise application evidence data. In this PR, an initial `supporting_evidence` attribute is added to the application schema. This is an array of documents with four fields (for the time being) `filename`, `s3_object_key` `file_size` `content_type`. The `application`, `application_returned` and `maat_application` fixtures are updated to return the new attribute. 
As the evidence upload work is currently behind a feature flag, the `supporting_evidence` field is not a required attribute.  
[CRIMAP-580](
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-580)
If you would like to test this, see [the apply pr](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/482) for instructions …

[CRIMAP-580] Add supporting evidence to schema

---

spec/fixtures/application/1.0/maat_application.json

Fixes error in [previous PR](https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/40) where `supporting_evidence` was being returned in the maat application fixture. However, `supporting_evidence` is not being exposed to MAAT
[CRIMAP-580](https://dsdmoj.atlassian.net/browse/CRIMAP-580)
[CRIMAP-580]: https://dsdmoj.atlassian.net/browse/CRIMAP-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove supporting evidence from maat application fixture

---

Gemfile.lock
lib/laa_crime_schemas/structs/base.rb
lib/laa_crime_schemas/structs/case_details.rb
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/laa_crime_schemas/structs/case_details_spec.rb

Two new optional JSON attributes have been added to the schema. Not added yet to the MAAT schema as, if needed, I'd rather do that as a separate change agreed with them.
Bumped some outdated gems.
Fixed a couple rubocop offences.
https://dsdmoj.atlassian.net/browse/CRIMAP-598

CRIMAP-598 Schema changes to support first court hearing

---

Gemfile.lock
lib/laa_crime_schemas/structs/document.rb
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/general/document.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/laa_crime_schemas/structs/document_spec.rb

Introduces new document attributes to track virus scan results
https://dsdmoj.atlassian.net/browse/CRIMAP-650
- is the current `VirusScanStatus` enum values appropriate?
- is this overkill?
- should `scan_provider` be locked down to `ClamAV` and `Other` ? Does anyone care?

[CRIMAP-650] Add new virus scan attributes

---

Gemfile.lock
lib/laa_crime_schemas/structs/income_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/means.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/means.json

Adds 2 new optional fields:
- `lost_job_in_custody` (yes/no)
- `date_job_lost` (e.g. 2023-10-01)
https://dsdmoj.atlassian.net/browse/CRIMAPP-129
PR in contrast to https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/57
Also removes tabs from means.json
Should the 2 new fields be grouped (not grouped at present) e.g.:
```
"lost_job": {
"lost_job_in_custody": "yes",
"date_job_lost": "2023-09-01"
}
```
This might be appealing in that both fields (lost_job_in_custody and date_lost_job) must be provided as there must always be a date IF the user has lost_job_in_custody = 'yes'.

[CRIMAP-129] Add 'job lost in custody' fields

---

Gemfile.lock
lib/laa_crime_schemas/structs/income_details.rb
lib/laa_crime_schemas/structs/means_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/means.json

Makes `income_details` fields optional to prevent unforced errors while new features are being developed.
https://dsdmoj.atlassian.net/browse/CRIMAPP-246
Caused by Sentry error on staging:
https://ministryofjustice.sentry.io/issues/4673356801/events/bf08339f3e9b41f9a145ca34194dda75/

[CRIMAP-246] Make income_details completely optional

---

Gemfile.lock
lib/laa_crime_schemas/structs/outgoings_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/means.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json
spec/fixtures/application/1.0/means.json
spec/laa_crime_schemas/structs/means_details_spec.rb

Adds new `income_tax_rate_above_threshold` field to `outgoings_details`
https://dsdmoj.atlassian.net/browse/CRIMAPP-224
N/A

[CRIMAP-224] Add income_tax_rate_above_threshold to Schema

---

Gemfile.lock
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
schemas/1.0/maat_application.json
schemas/1.0/pruned_application.json

Add PSE and CIFC applications types to schema.
[CRIMAPP-87](https://dsdmoj.atlassian.net/browse/CRIMAPP-87)
As concluded post spike, PSE and CIFC will be stored in the CrimeApplication table.
[CRIMAPP-87]: https://dsdmoj.atlassian.net/browse/CRIMAPP-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-290 add PSE to application type

---

Gemfile.lock
lib/laa_crime_schemas/structs/base_application.rb
lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/structs/document.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/post_submission_evidence.json

As part of the work to introduce post submission evidence functionality to apply and review, some crime application fields that were previously mandatory have now been made optional fields. 
This makes the schema more flexible in anticipation for new application types being added in the future (e.g. change in financial circumstances) that do not require fields like a `case_type` or `date_stamp`
Also adds a notes field to collect notes as part of a pse application and a fixture for a post submission evidence application for testing in apply
[CRIMAPP-290](https://dsdmoj.atlassian.net/browse/CRIMAPP-290)
[CRIMAPP-290]: https://dsdmoj.atlassian.net/browse/CRIMAPP-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-290 Add pse fields and make schema more flexible

---

Gemfile.lock
lib/laa_crime_schemas/structs/base_application.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
schemas/1.0/pruned_application.json

Add "reviewed_at" to the schema and structs.
[CRIMAPP-356](https://dsdmoj.atlassian.net/browse/CRIMAPP-356)
To determine when to display the PSE link, Apply needs to know whether an application has been reviewed. In our initial spike, we used the "review_status", but now we prefer "reviewed_at" as it discloses less internal Review information. Additionally, this update includes the addition of a "readOnly" flag to attributes owned by the datastore on the application schema. Note: the "readOnly" flag is not applied to the pruned schema, as this schema is entirely readOnly.
[CRIMAPP-356]: https://dsdmoj.atlassian.net/browse/CRIMAPP-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-356 Add reviewed_at to structs and schema

---

spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/post_submission_evidence.json

Small changes to fixture files for PSE testing. Assigns a unique id to the pse application fixture and adds the `application_id` of the standard initial application as the `parent_id` of the pse application. Also adds the `application_type` to the relevant fields

[CRIMAPP-290] Amend fixtures for pse testing

---

Gemfile.lock
lib/laa_crime_schemas/structs/document.rb
lib/laa_crime_schemas/version.rb
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/post_submission_evidence.json

Application type is no longer required on documents
This presence of 'application_type' on documents was causing a breaking change on current Apply.

Remove application_type from document

---

lib/laa_crime_schemas/structs/base_application.rb
schemas/1.0/application.json
schemas/1.0/pruned_application.json
spec/laa_crime_schemas/structs/pruned_application_spec.rb

The fields `reviewed_at`, `returned_at`, and `date_stamp` are now allowed to be null.
[CRIMAPP-356](https://dsdmoj.atlassian.net/browse/CRIMAPP-356)
With the introduction of PSE, `date_stamp` is now permitted to be null in the schema. Additionally, the schema now allows for `reviewed_at` and `returned_at` to be present and null. This oversight was tolerated due to submitted applications not validating against the JSON schema.
I have not update the release version for this change.
[CRIMAPP-356]: https://dsdmoj.atlassian.net/browse/CRIMAPP-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

reviewed_at, returned_at, and date_stamp can all be null

---

Gemfile.lock
lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
spec/fixtures/application/1.0/post_submission_evidence.json

Rename 'notes' 'additional_information'
We used 'notes' in the spike but 'additional_information' matches the domain better. No production services use 'notes'

Rename 'notes' 'additional_information'

---

Gemfile.lock
lib/laa_crime_schemas/structs/case_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json

Allow null for `cases.has_case_concluded` attribute to support old applications
https://dsdmoj.atlassian.net/browse/CRIMAPP-310

CRIMAPP-310 Allow null for has_case_concluded

---

Gemfile.lock
lib/laa_crime_schemas/structs/case_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json

Add `is_client_remanded` attributes
Add `is_client_remanded` and the `date_client_remanded` to struct, schema and fixtures
https://dsdmoj.atlassian.net/browse/CRIMAPP-314
This change is required for [laa-apply-for-criminal-legal-aid](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid) specs to pass

CRIMAPP-314 Add is_client_remanded attributes

---

lib/laa_crime_schemas/structs/amount.rb
lib/laa_crime_schemas/types/types.rb
schemas/1.0/means.json
spec/fixtures/application/1.0/means.json
spec/laa_crime_schemas/structs/means_details_spec.rb

Adds `metadata.case_reference` to `Amount` to allow Outgoing payments
https://dsdmoj.atlassian.net/browse/CRIMAPP-218
Outgoing types have been updated to match Apply but will need clarifying

[CRIMAPP-218] Add case reference field for outgoings misc payments

---

schemas/1.0/means.json

Amends Schema `HOUSING_PAYMENT_TYPES` to use correct `board_lodgings` type. 
https://dsdmoj.atlassian.net/browse/CRIMAPP-601
Current

[CRIMAPP-601] Update means.json

---

Gemfile.lock
lib/laa_crime_schemas/structs/investment.rb
lib/laa_crime_schemas/structs/saving.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/general/investment.json
schemas/1.0/general/saving.json
spec/fixtures/application/1.0/means.json
spec/laa_crime_schemas/structs/investment_spec.rb
spec/laa_crime_schemas/structs/saving_spec.rb

Savings, Investments and other assets were storing ownership_type on different attributes (holder, account_holder etc).

Consistent names for ownership

---

Gemfile.lock
lib/laa_crime_schemas/structs/capital_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/means.json
spec/fixtures/application/1.0/means.json
spec/laa_crime_schemas/structs/capital_details_spec.rb

Add trust fund attributes to capital details
[CRIMAPP-586](https://dsdmoj.atlassian.net/browse/CRIMAPP-586)
[CRIMAPP-586]: https://dsdmoj.atlassian.net/browse/CRIMAPP-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-586] Add trust fund attributes to schema

---

Gemfile.lock
lib/laa_crime_schemas/structs/capital_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/means.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/means.json
spec/laa_crime_schemas/structs/capital_details_spec.rb

Also renames `yearly_dividend` to `trust_fund_yearly_dividend`
[CRIMAPP-505](https://dsdmoj.atlassian.net/browse/CRIMAPP-505)
[CRIMAPP-505]: https://dsdmoj.atlassian.net/browse/CRIMAPP-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add frozen income assets savings attribute to capital details

---

Gemfile.lock
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
spec/fixtures/application/1.0/application.json

Adds `food_amount` and `board_amount` fields to fix failing specs in [review pr](https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/563) 
Also updates income benefit and payment types to be shared across apply and review

Add required board and lodgings fields

---

lib/laa_crime_schemas/structs/capital_details.rb
spec/fixtures/application/1.0/application.json

Add **capitals.has_no_other_assets** to `capital_details`
https://dsdmoj.atlassian.net/browse/CRIMAPP-506

CRIMAPP-506 Add support for has_no_other_assets in capital

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat/means.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/maat_application.json
spec/fixtures/application/1.0/means.json
spec/laa_crime_schemas/structs/means_details_spec.rb

Rename some keys and values on MAAT schema and fixture to align with current naming:
`benefits` > `income_benefits`
`other_income` > `income_payments`
`type` > `payment_type`
`legal_aid` > `legal_aid_contribution`
Remove housing outgoing payment enum `housing` and add `rent`/`mortgage`/`board_and_lodging`
Remove `housing_payment_type` from MAAT a this is now captured in the object in the outgoings array and needless to send

Rename keys to income_benefits and income_payments

---

Gemfile.lock
lib/laa_crime_schemas/structs/capital_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/means.json
spec/laa_crime_schemas/structs/capital_details_spec.rb

As it is possible for applications to not go through the full capital means assessment (in the case of applications that are not either way, indictable, already in crown court cases), the premium bonds question may not be asked and can therefore be null 
The schema is updated to support this
The `has_frozen_income_assets` attribute was also added to the means json schema as it was missing

Update capital details schema

---

schemas/1.0/maat/means.json

Replace metadata on MAAT schema
Datastore will now transform the income_payements and income_benefits to have details extracted from metadata, but not delete metadata as originally considered

Replace metadata on MAAT schema

---

Gemfile.lock
lib/laa_crime_schemas/structs/capital_details.rb
lib/laa_crime_schemas/structs/income_details.rb
lib/laa_crime_schemas/structs/outgoings_details.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/means.json
spec/fixtures/application/1.0/means.json

Adds attributes to means details that enable `no` answers to be persisted in apply and absent records to be displayed in apply and review 
[CRIMAPP-701](https://dsdmoj.atlassian.net/browse/CRIMAPP-701)
[CRIMAPP-702](https://dsdmoj.atlassian.net/browse/CRIMAPP-702)
[CRIMAPP-735](https://dsdmoj.atlassian.net/browse/CRIMAPP-735)
[CRIMAPP-701]: https://dsdmoj.atlassian.net/browse/CRIMAPP-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-702]: https://dsdmoj.atlassian.net/browse/CRIMAPP-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-735]: https://dsdmoj.atlassian.net/browse/CRIMAPP-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-735] Add additional means attributes

---

Gemfile.lock
lib/laa_crime_schemas/structs/applicant.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/general/applicant.json
spec/fixtures/application/1.0/application.json
spec/fixtures/application/1.0/application_returned.json

Renames `relationship_to_someone_else` to `relationship_to_owner_of_usual_home_address` following code review
[CRIMAPP-776](https://dsdmoj.atlassian.net/browse/CRIMAPP-776)
[CRIMAPP-776]: https://dsdmoj.atlassian.net/browse/CRIMAPP-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-776] Rename residence type relationship attribute

---

Gemfile.lock
lib/laa_crime_schemas/structs/base_application.rb
lib/laa_crime_schemas/structs/case_details.rb
lib/laa_crime_schemas/structs/crime_application.rb
lib/laa_crime_schemas/structs/provider_details.rb
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
spec/laa_crime_schemas/structs/provider_details_spec.rb

On Apply providers now review a draft JSON application before they submit to the datastore. This change updates the Structs so they can be used to show an in progress application. It purposefully does not update the json-schema, which still require a submissable application.
[CRIMAPP-846](https://dsdmoj.atlassian.net/browse/CRIMAPP-846)
[CRIMAPP-846]: https://dsdmoj.atlassian.net/browse/CRIMAPP-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-846 Structs support 'in_progress' applications.

---

schemas/1.0/maat/means.json
schemas/1.0/means.json
spec/laa_crime_schemas/types/types_spec.rb

Remove `self_assessment_tax_bill` from outgoings payments.
We decided to create `self_assessment_tax_bill` attributes in income table. Here is the PR: [PR](https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/925)

NO TICKET: Remove self_assessment_tax_bill attribute from outgoings payment types

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat_application.json

Fixes issue reported with injecting partner details for maat. The `involvement_in_case` attribute incorrectly includes the value `no_involvement` rather than `none`

Amend involvement in case type error

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat/means.json
spec/fixtures/application/1.0/maat_application.json

- We are saving `income < 12,475`, in **income_payments** table where payment_type == 'employment'
- We are saving `income > 12,475`, in **employments** table
MATT schema doesn't care about above separation so we have to send `income < 12,475` or `income  >  12,475`  as an **employment_income_payments**

Update schema to remove employment as income payment

---

Gemfile.lock
lib/laa_crime_schemas/structs/base_application.rb
lib/laa_crime_schemas/structs/income_details.rb
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
spec/laa_crime_schemas/structs/income_details_spec.rb

Set default values for parter and applicant employment types
No longer require status for CrimeApplication struct
[CRIMAPP-1069](https://dsdmoj.atlassian.net/browse/CRIMAPP-1069)
[CRIMAPP-1069]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1069] Set default values for employment_type

---

Gemfile.lock
lib/laa_crime_schemas/structs/investment.rb
lib/laa_crime_schemas/structs/national_savings_certificate.rb
lib/laa_crime_schemas/structs/partner.rb
lib/laa_crime_schemas/structs/person.rb
lib/laa_crime_schemas/structs/saving.rb
lib/laa_crime_schemas/version.rb
spec/laa_crime_schemas/structs/codefendant_spec.rb
spec/laa_crime_schemas/structs/crime_application_spec.rb
spec/laa_crime_schemas/structs/pruned_application_spec.rb

v 1.2.0
Structs support draft applications. 
[CRIMAPP-1230](https://dsdmoj.atlassian.net/browse/CRIMAPP-1230)
This change is to allow them to be used an Apply for draft applications (see: https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/1085 )
[CRIMAPP-1230]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1230 Structs support draft applications

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat/means.json
spec/fixtures/application/1.0/maat_application.json

MAAT doesn't require the following `payment_type` enums for `income_payments` and `income_benefits`
- student_loan_grant
- board_from_family
- rent
- financial_support_with_access
- from_friends_relatives
- jsa
https://dsdmoj.atlassian.net/browse/CRIMAPP-1119

CRIMAPP-1119 Update enums for income payments and benefits

---

schemas/1.0/maat/means.json

Include applicant and partner dividends from a trust fund to total value of 'Other Income' in MAAT
OTHER_INCOME_PAYMENT_TYPES(including dividend)
- student_loan_grant
- board_from_family
- rent
- financial_support_with_access
- from_friends_relatives
- other
- trust_fund_dividend
https://dsdmoj.atlassian.net/browse/CRIMAPP-1318
- Trust fund dividend attributes (`trust_fund_yearly_dividend`, `partner_trust_fund_yearly_dividend`) belongs to `capital_details` object. To add trust fund dividends to 'other_incomes' we need to pass these attributes to `income_details` object. 
- Created `dividends` object by including trust fund dividend attributes and merged it with `income_details` object
Here is the reference PR: https://github.com/ministryofjustice/laa-criminal-applications-datastore/pull/31 …

CRIMAPP-1318  Dividends from a trust fund - considered as ‘income’ and needs to be added to the total value of 'Other Income' in MAAT

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat_application.json
spec/fixtures/application/1.0/maat_application.json

- Validation error occurs when correspondence_address_type is not present. So we need to make it optional as   `correspondence_address_type` is not required for 'Appeal to crown court' applications
- Exposing  :appeal_usn attribute (may be required for MAAT)
https://dsdmoj.atlassian.net/browse/CRIMAPP-1288

CRIMAPP-1288 Appeal to crown court applications not injecting to MAAT

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
schemas/1.0/maat_application.json

Validation error occurs when `#/case_details/hearing_date` is not present. So we need to make it optional as `hearing_date` is not required for **A change in financial circumstances** >  **Appeal to crown court** applications
https://dsdmoj.atlassian.net/browse/CRIMAPP-1288

CRIMAPP-1288 Appeal to crown court applications not injecting to maat with missing hearing date

---

Gemfile.lock
lib/laa_crime_schemas/structs/decision.rb
lib/laa_crime_schemas/validator.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/general/decision.json
spec/laa_crime_schemas/structs/decision_spec.rb
spec/laa_crime_schemas/validator_spec.rb

1. Added `case_id` to the Decision struct/schema.
2. Regenerated the `decision` schema using `JSON.pretty_generate`.
3. Added the `list` parameter to the validator to enable it to validate arrays of objects against a schema.
[CRIMAPP-1398](https://dsdmoj.atlassian.net/browse/CRIMAPP-1398)
[CRIMAPP-1398]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1398] Add case_id to Decision

---

Gemfile.lock
lib/laa_crime_schemas/structs/amount.rb
lib/laa_crime_schemas/structs/codefendant.rb
lib/laa_crime_schemas/structs/investment.rb
lib/laa_crime_schemas/structs/national_savings_certificate.rb
lib/laa_crime_schemas/structs/property.rb
lib/laa_crime_schemas/version.rb

Fixes a couple of sentry errors linked in the ticket.
Users are being thrown errors on the evidence upload and review page when there are incomplete employment, Investment, co-defendant, saving and national saving certificate records. This is because the application's data is used to recreate a draft version of the application based on the schema. For some attributes, nil values were not permitted and so errors were being thrown. Nil values are now permitted
[dsdmoj.atlassian.net/browse/CRIMAPP-1453](https://dsdmoj.atlassian.net/browse/CRIMAPP-1453)

[CRIMAPP-1453] LAA-APPLY-FOR-CRIMINAL-LEGAL-AID-2Y fix

---

lib/laa_crime_schemas/structs/decision.rb
lib/laa_crime_schemas/types/types.rb
schemas/1.0/general/decision.json
spec/laa_crime_schemas/structs/decision_spec.rb
spec/laa_crime_schemas/structs/test_result_spec.rb
spec/laa_crime_schemas/validator_spec.rb

- Use past tense for test result and decision types.
- Store the overall decision, as shown in eForms, alongside the simplified data model for funding decisions in Crime Apply/Review. This ensures the overall result is available if needed by users.
- Add descriptions to decision attributes in the JSON schema
https://dsdmoj.atlassian.net/browse/CRIMAPP-1490
I have delete the v1.5.0 which this PR will replace.

CRIMAPP 907 revise decision data model

---

Gemfile.lock
lib/laa_crime_schemas/version.rb
spec/fixtures/application/1.0/application.json
spec/laa_crime_schemas/structs/case_details_spec.rb

A minor update to the application fixture to include `partner_other_charge`.
[CRIMAPP-1578](https://dsdmoj.atlassian.net/browse/CRIMAPP-1578)
[CRIMAPP-1578]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRIMAPP-1578] Update application fixture

---

Gemfile.lock
lib/laa_crime_schemas/structs/decision.rb
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/general/decision.json

Store `overall_result` as a type
[CRIMAPP-1597](https://dsdmoj.atlassian.net/browse/CRIMAPP-1597)
The initial plan was to store MAAT strings directly in the datastore `overall_result`, as MAAT is the source of truth for decisions and its logic is complex. However, testing has shown that these strings do not fully meet providers' needs and may cause confusion.
Instead, we will store a constant representing the overall result, which clients can translate into text as needed. This result will combine the funding_decision with any relevant qualifications that help providers understand the next steps.
[CRIMAPP-1597]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1597 restrict values for decision#overall_result

---

Gemfile.lock
lib/laa_crime_schemas/structs/decision.rb
lib/laa_crime_schemas/types/types.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/general/decision.json
spec/laa_crime_schemas/structs/decision_spec.rb

This PR introduces an `overall_result` type of `refused_ineligible` it also replaces `court_type` with `assessment_rules`, so that all the assessment rules used for the means test can be differentiated.
Add the following assessment types: Crown Court, Magistrates Court, Non-means, Committal for sentence , Appeal to Crown Court
[CRIMAPP-1630](https://dsdmoj.atlassian.net/browse/CRIMAPP-1630)
[CRIMAPP-1630]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRIMAPP-1630 handle all assessment rules and introduce refused_ineligible

---

Gemfile.lock
lib/laa_crime_schemas/structs/base_application.rb
lib/laa_crime_schemas/version.rb
schemas/1.0/application.json
schemas/1.0/pruned_application.json
spec/laa_crime_schemas/structs/crime_application_spec.rb

Add `review_status` as a read only attribute
https://dsdmoj.atlassian.net/browse/CRIMAPP-1653
Required to determined  the decision status of an application from the Datastore response.

[CRIMAPP-1653] add review_status read only attr
